import React from "react";
import ReactDOM from "react-dom";
import { App } from "./app";
import { GlobalStyle } from "./global-style";
import reportWebVitals from "./reportWebVitals";

ReactDOM.render(
  <React.StrictMode>
    <GlobalStyle />
    <App />
  </React.StrictMode>,
  document.getElementById("root")
);

// This was generated by default by create react app for web
// performance tracking
reportWebVitals();
